language: python
python:
  - "3.5"
before_install:
    # No GPU on the build server
    - sed -i 's/tensorflow-gpu/tensorflow/g' ./requirements.txt
install:
  - pip install -r requirements.txt
script:
  - nosetests

